#!/bin/sh

DIR=${1-'./'}

cd $DIR || exit 1

# Optionally try to install various dependencies so licensefinder can use the package manager without errors
if [ -f 'Gemfile' ]; then
  bundle install || true
fi

if [ -f 'mix.exs' ]; then
  mix deps.get || true
fi

if [ -f 'yarn.lock' ]; then
  yarn install || true
elif [ -f 'package.json' ]; then
  npm install || true
fi

license_finder
